### ISSUE TITLE
Tailwind CSS Tipography

### ISSUE THREAD

**Issue by teragramgius** [michael-andreuzza/astromax#1]
Hello hello!
The first error while I'm running the preview is:
`Cannot read properties of undefined (reading 'postcss')`
then I install:
`npm install @astrojs/tailwind tailwindcss`
and then run `preview`
but it gives me an error then:
`Cannot find module '@tailwindcss/typography'`

**Comment by michael-andreuzza** [comment]
You have to update dependencies.
 npm install
 ncu -u   
npm install

**Comment by michael-andreuzza** [comment]
Closing issue
