### ISSUE TITLE
Can you guide me with this error? It has something to do with the manifest file

### ISSUE THREAD

**Issue by ghost** [michael-andreuzza/astromax#2]
<img width="746" alt="image" src="https://github.com/michael-andreuzza/astromax/assets/153914252/3556fa6d-ab58-4520-af47-04244616dd26">

**Comment by michael-andreuzza** [comment]
That's because you need to add a web manifest, if you want to, if not ignore it.
It gives error, because there isn't., hence it can find it.

Have nice day!

**Comment by michael-andreuzza** [comment]
Not an error.
